windowrulev2 = float, class:^(Thunar)$, title:^(File Operation Progress)$

# Zen Browser Picture-in-Picture window
windowrulev2 = float, class:^(zen)$, title:^(Picture-in-Picture)$
windowrulev2 = pin, class:^(zen)$, title:^(Picture-in-Picture)$
windowrulev2 = move 100%-670 100%-420, class:^(zen)$, title:^(Picture-in-Picture)$
windowrulev2 = size 650 400, class:^(zen)$, title:^(Picture-inPicture)$

# Steam windows
windowrulev2 = float, class:^(Steam)$, title:^(Friends List)$
windowrulev2 = float, class:^(Steam)$, title:^(Steam - News)$

# Pavucontrol
windowrulev2 = float, class:^(Pavucontrol)$

# Bluetooth Manager (assuming Blueman)
windowrulev2 = float, class:^(Blueman-manager)$
