# Catppuccin Mocha Theme - Hyprland Colors
$themeAccent = rgb(89b4fa)
$themeForeground = rgb(cdd6f4)
$themeBackground = rgb(1e1e2e)

general {
    col.active_border = rgba(89b4facc)
}

group {
    col.border_active = rgba(89b4facc)
}
