# Gruvbox Theme - Hyprland Colors
$themeAccent = rgb(83a598)
$themeForeground = rgb(ebdbb2)
$themeBackground = rgb(282828)

general {
    col.active_border = rgb(83a598)
}

group {
    col.border_active = rgb(83a598)
}
