# Monochrome Theme - Hyprland Colors
$themeAccent = rgb(808080)
$themeForeground = rgb(e0e0e0)
$themeBackground = rgb(121212)

general {
    col.active_border = rgb(808080)
}

group {
    col.border_active = rgb(808080)
}
