# Nord Theme - Hyprland Colors
$themeAccent = rgb(88c0d0)
$themeForeground = rgb(eceff4)
$themeBackground = rgb(2e3440)

general {
    col.active_border = rgba(88c0d0cc)
}

group {
    col.border_active = rgba(88c0d0cc)
}
