# Everforest Theme - Hyprland Colors
$themeAccent = rgb(a7c080)
$themeForeground = rgb(d3c6aa)
$themeBackground = rgb(272e33)

general {
    col.active_border = rgb(a7c080)
}

group {
    col.border_active = rgb(a7c080)
}
